################################################
## 系统 相关配置
################################################

debug: true
interval: 1

################################################
## clickhouse 相关配置
################################################
clickhouse:
    user: default
    password: 123456
    host: 192.168.31.123
    port: 9000
    database: monitor
    nums: 1000
